// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="processB,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu7p-flvb2104-1-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.857500,HLS_SYN_LAT=16,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=26,HLS_SYN_LUT=148,HLS_VERSION=2018_2}" *)

module processB (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bx_V,
        bx_o_V,
        bx_o_V_ap_vld,
        inmem_address0,
        inmem_ce0,
        inmem_q0,
        outmem_address0,
        outmem_ce0,
        outmem_we0,
        outmem_d0
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [1:0] bx_V;
output  [1:0] bx_o_V;
output   bx_o_V_ap_vld;
output  [4:0] inmem_address0;
output   inmem_ce0;
input  [31:0] inmem_q0;
output  [4:0] outmem_address0;
output   outmem_ce0;
output   outmem_we0;
output  [31:0] outmem_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg inmem_ce0;
reg outmem_ce0;
reg outmem_we0;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] tmp_2_fu_183_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
reg    bx_o_V_1_ack_in;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage0_11001;
reg   [1:0] bx_o_V_1_data_reg;
reg    bx_o_V_1_vld_reg;
reg    bx_o_V_1_vld_in;
reg   [0:0] do_init_reg_93;
reg   [1:0] bx_V2_rewind_reg_109;
reg   [3:0] i1_reg_123;
reg   [1:0] bx_V2_phi_reg_137;
wire   [63:0] tmp_6_cast_fu_178_p1;
reg   [63:0] tmp_6_cast_reg_204;
reg   [0:0] tmp_2_reg_214;
wire   [3:0] i_fu_189_p2;
reg   [3:0] i_reg_218;
reg    ap_block_pp0_stage0_subdone;
reg   [0:0] ap_phi_mux_do_init_phi_fu_97_p6;
wire    ap_block_pp0_stage0;
reg   [1:0] ap_phi_mux_bx_V2_rewind_phi_fu_113_p6;
reg   [3:0] ap_phi_mux_i1_phi_fu_127_p6;
reg   [1:0] ap_phi_mux_bx_V2_phi_phi_fu_142_p4;
wire   [1:0] ap_phi_reg_pp0_iter0_bx_V2_phi_reg_137;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] tmp_fu_156_p1;
wire   [4:0] tmp_4_fu_160_p3;
wire   [5:0] tmp_5_cast_fu_168_p1;
wire   [5:0] tmp_cast_fu_152_p1;
wire   [5:0] tmp_6_fu_172_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_133;
reg    ap_condition_119;
reg    ap_condition_45;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 bx_o_V_1_data_reg = 2'd0;
#0 bx_o_V_1_vld_reg = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_45)) begin
        if ((ap_phi_mux_do_init_phi_fu_97_p6 == 1'd0)) begin
            bx_V2_phi_reg_137 <= ap_phi_mux_bx_V2_rewind_phi_fu_113_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_97_p6 == 1'd1)) begin
            bx_V2_phi_reg_137 <= bx_V;
        end else if ((1'b1 == 1'b1)) begin
            bx_V2_phi_reg_137 <= ap_phi_reg_pp0_iter0_bx_V2_phi_reg_137;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (bx_o_V_1_vld_reg == 1'b0) & (bx_o_V_1_vld_in == 1'b1))) begin
        bx_o_V_1_vld_reg <= 1'b1;
    end else if (((bx_o_V_1_vld_in == 1'b0) & (1'b1 == 1'b1) & (bx_o_V_1_vld_reg == 1'b1))) begin
        bx_o_V_1_vld_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_2_reg_214 == 1'd0))) begin
        do_init_reg_93 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_reg_214 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        do_init_reg_93 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_2_reg_214 == 1'd0))) begin
        i1_reg_123 <= i_reg_218;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_reg_214 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        i1_reg_123 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_2_reg_214 == 1'd0))) begin
        bx_V2_rewind_reg_109 <= bx_V2_phi_reg_137;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (bx_o_V_1_vld_reg == 1'b0) & (bx_o_V_1_vld_in == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (bx_o_V_1_vld_in == 1'b1) & (bx_o_V_1_vld_reg == 1'b1)))) begin
        bx_o_V_1_data_reg <= ap_phi_mux_bx_V2_phi_phi_fu_142_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_218 <= i_fu_189_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_2_reg_214 <= tmp_2_fu_183_p2;
        tmp_6_cast_reg_204[5 : 0] <= tmp_6_cast_fu_178_p1[5 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_reg_214 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_133)) begin
        if ((ap_phi_mux_do_init_phi_fu_97_p6 == 1'd0)) begin
            ap_phi_mux_bx_V2_phi_phi_fu_142_p4 = ap_phi_mux_bx_V2_rewind_phi_fu_113_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_97_p6 == 1'd1)) begin
            ap_phi_mux_bx_V2_phi_phi_fu_142_p4 = bx_V;
        end else begin
            ap_phi_mux_bx_V2_phi_phi_fu_142_p4 = ap_phi_reg_pp0_iter0_bx_V2_phi_reg_137;
        end
    end else begin
        ap_phi_mux_bx_V2_phi_phi_fu_142_p4 = ap_phi_reg_pp0_iter0_bx_V2_phi_reg_137;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (tmp_2_reg_214 == 1'd0))) begin
        ap_phi_mux_bx_V2_rewind_phi_fu_113_p6 = bx_V2_phi_reg_137;
    end else begin
        ap_phi_mux_bx_V2_rewind_phi_fu_113_p6 = bx_V2_rewind_reg_109;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_119)) begin
        if ((tmp_2_reg_214 == 1'd1)) begin
            ap_phi_mux_do_init_phi_fu_97_p6 = 1'd1;
        end else if ((tmp_2_reg_214 == 1'd0)) begin
            ap_phi_mux_do_init_phi_fu_97_p6 = 1'd0;
        end else begin
            ap_phi_mux_do_init_phi_fu_97_p6 = do_init_reg_93;
        end
    end else begin
        ap_phi_mux_do_init_phi_fu_97_p6 = do_init_reg_93;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_119)) begin
        if ((tmp_2_reg_214 == 1'd1)) begin
            ap_phi_mux_i1_phi_fu_127_p6 = 4'd0;
        end else if ((tmp_2_reg_214 == 1'd0)) begin
            ap_phi_mux_i1_phi_fu_127_p6 = i_reg_218;
        end else begin
            ap_phi_mux_i1_phi_fu_127_p6 = i1_reg_123;
        end
    end else begin
        ap_phi_mux_i1_phi_fu_127_p6 = i1_reg_123;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_fu_183_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((bx_o_V_1_vld_reg == 1'b0) | ((1'b1 == 1'b1) & (bx_o_V_1_vld_reg == 1'b1)))) begin
        bx_o_V_1_ack_in = 1'b1;
    end else begin
        bx_o_V_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_fu_183_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bx_o_V_1_vld_in = 1'b1;
    end else begin
        bx_o_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inmem_ce0 = 1'b1;
    end else begin
        inmem_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        outmem_ce0 = 1'b1;
    end else begin
        outmem_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        outmem_we0 = 1'b1;
    end else begin
        outmem_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_reset_idle_pp0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((bx_o_V_1_ack_in == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((bx_o_V_1_ack_in == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((bx_o_V_1_ack_in == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (bx_o_V_1_ack_in == 1'b0);
end

always @ (*) begin
    ap_condition_119 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0));
end

always @ (*) begin
    ap_condition_133 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0));
end

always @ (*) begin
    ap_condition_45 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_bx_V2_phi_reg_137 = 'bx;

assign bx_o_V = bx_o_V_1_data_reg;

assign bx_o_V_ap_vld = bx_o_V_1_vld_reg;

assign i_fu_189_p2 = (4'd1 + ap_phi_mux_i1_phi_fu_127_p6);

assign inmem_address0 = tmp_6_cast_fu_178_p1;

assign outmem_address0 = tmp_6_cast_reg_204;

assign outmem_d0 = inmem_q0 << 32'd1;

assign tmp_2_fu_183_p2 = ((ap_phi_mux_i1_phi_fu_127_p6 == 4'd15) ? 1'b1 : 1'b0);

assign tmp_4_fu_160_p3 = {{tmp_fu_156_p1}, {4'd0}};

assign tmp_5_cast_fu_168_p1 = tmp_4_fu_160_p3;

assign tmp_6_cast_fu_178_p1 = tmp_6_fu_172_p2;

assign tmp_6_fu_172_p2 = (tmp_5_cast_fu_168_p1 + tmp_cast_fu_152_p1);

assign tmp_cast_fu_152_p1 = ap_phi_mux_i1_phi_fu_127_p6;

assign tmp_fu_156_p1 = ap_phi_mux_bx_V2_phi_phi_fu_142_p4[0:0];

always @ (posedge ap_clk) begin
    tmp_6_cast_reg_204[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //processB
